apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: web-os
  labels:
    app.kubernetes.io/name: web-os-api
    app.kubernetes.io/part-of: web-os
spec:
  selector:
    app.kubernetes.io/name: web-os-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
